### ISSUE TITLE
es6 export / import issue?

### ISSUE THREAD

**Issue by weilinzung** [cedx/akismet.js#16]
```
/node_modules/@cedx/akismet/lib/index.js:1
export * from './author.js';
^^^^^^

SyntaxError: Unexpected token export

```

**Comment by cedx** [comment]
You are using an outdated Node.js version (i.e. not supporting [ES modules](https://nodejs.org/api/esm.html), or without the `--experimental-modules` flag enabled).

The latest release of this library requires Node.js v14 because it only uses ES modules (Node.js v12 and 13 should be fine).

If you can't upgrade to Node.js v14, just use a previous release of this library: the [version 13.0.1](https://www.npmjs.com/package/@cedx/akismet/v/13.0.1) still uses CommonJS modules.

**Comment by weilinzung** [comment]
@cedx cool. thanks to the info!
