### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by chriscoyier** [cedx/akismet.js#9]
If I pull this and `npm install` and `npm run prepare`, it errors:

<img width="1076" alt="Screen Shot 2019-05-28 at 1 23 55 PM" src="https://user-images.githubusercontent.com/69156/58509633-dc4bdb80-814b-11e9-81cd-72999312a673.png">

and the CDN builds seem dead too:
https://unpkg.com/@cedx/akismet@13.0.1/build/akismet.min.js

I don't know enough to know why.

**Comment by cedx** [comment]
The famous Chris Coyier is looking at my project !!! I am flattered.
As you've seen, this project is currently in an unstable state :

- the npm install does not work because the project is being ported to ES modules, but I've not found the time to finish.
- the CDN build does not work because the online documentation refers to the **next** version... which was never released 😞

But I have good news: I decided to work on it again! Give me a few days to fix all these issues.

**Comment by cedx** [comment]
It took a looooooonnnnnng time (I'm a very busy person)... but all issues were finally resolved in the latest release (v14.0.0). Beware: some breaking changes were introduced.

### Dropped the browser client
Akismet has never supported CORS headers, and it looks like it will not change. So using the browser client needed a complicated setup (i.e. use an intermediate proxy server). It was also a bit hard to maintain an isomorphic package.
**Now, you can only use this package in a Node.js application.** 😢 

### Using ECMAScript modules
This is a major change: to consume this package, you need a recent Node.js runtime. Either version 13, or version 12 with the `--experimental-modules` flag enabled.

### Changed the return type of the `Client.checkComment()` method
Previously, this method returned a boolean (i.e. the comment is a spam... or not). Now, it returns a [`CheckResult` value](https://dev.belin.io/akismet.js/api/enums/checkresult.html).
The Akismet API sometimes includes a `X-akismet-pro-tip` HTTP header telling if a comment is "pervasive" spam and can be safely discarded. The new method implementation allows to handle this scenario.
